Shader "Unlit/UnlitShaderExample"
{
    Properties //input
    {
        _MainTex ("Texture", 2D) = "white" {}
        _BlockTexs("Block Textures", 2DArray) = "" {}
        [PerRendererData] _Width("Width", Int) = 1
        [PerRendererData] _Height("Height", Int) = 1
        
    }
    SubShader 
    {
        Tags { "RenderType"="Transparent" "Queue"="Transparent"}
        ZWrite Off
        Blend SrcAlpha OneMinusSrcAlpha

        Pass
        {
            CGPROGRAM
            // Upgrade NOTE: excluded shader from DX11, OpenGL ES 2.0 because it uses unsized arrays
        #pragma exclude_renderers d3d11 gles
            #pragma vertex vert
            #pragma fragment frag
            #pragma require 2darray

            #include "UnityCG.cginc"

            //auto filled out by unity
            struct MeshData //per-vertex mex data
            {
                float4 vertex : POSITION; //vertex position
                // float3 normals : NORMAL;
                float4 color : COLOR;
                // float4 tangent : TANGENT;
                float2 uv : TEXCOORD0; //uv0 coordinants
                // float2 uv1 : TEXCOORD1; //uv1 coordinants
            };

            struct v2f 
            {
                float4 vertex : SV_POSITION; // clip space position
                float2 uv : TEXCOORD0; //can be wahtever you want
                float4 color  : COLOR;
                // float2 uv : TEXCOORD1; //can be wahtever you want
                // float2 uv : TEXCOORD2; //can be wahtever you want
                // float2 uv : TEXCOORD3; //can be wahtever you want
                // float2 uv : TEXCOORD4; //can be wahtever you want
            };

            struct BlockTypeRenderData
            {
                int texIndex;
                int animated;
                int numFrames;
                float fps;
            };

            struct BlockRenderData
            {
                int typeID;
                int rotated;
            };
            
            sampler2D _MainTex;
            float4 _Color;
            float _Width;
            float _Height;
            StructuredBuffer<BlockRenderData> _BlockDataBuffer;
            StructuredBuffer<BlockTypeRenderData> _BlockTypeDataBuffer;

            v2f vert (MeshData v)
            {
                v2f o;
                o.vertex = UnityObjectToClipPos(v.vertex); // local space to clip space
                o.uv = v.uv;
                o.color = v.color;
                return o;
            }

            //bool 0 1
            //int
            // float (32 bit float)
            //half (16 bit float)
            //fixed (lower precision [12?])
            //float4 -> half4 -> fix4
            //float4x4 -> half4x4
            
            UNITY_DECLARE_TEX2DARRAY(_BlockTexs);
            
             fixed4 frag (v2f i) : SV_Target
             {
                 const float time = _Time.y;
                 const float2 uv = i.uv;
                 
                 const float2 block_uv = float2(uv.x * _Width, uv.y * _Height);

                 const float2 tex_uv = fmod(block_uv, 1);

                 const int2 array_uv = int2((int) block_uv.x, (int) block_uv.y);

                 const int block_index = array_uv.y * _Width + array_uv.x;

                 const BlockRenderData block = _BlockDataBuffer[block_index];

                 const BlockTypeRenderData type = _BlockTypeDataBuffer[block.typeID];

                 // type.animated is 0 if there is no animation so it will destroy any value generated by the rest of it
                 const float texIndex = type.texIndex + type.animated * fmod(floor(time * type.fps), (float) type.numFrames);

                 const float2 adjusted_tex_uv = (block.rotated ^ 1) * tex_uv + block.rotated * float2(tex_uv.y, tex_uv.x);
                 
                 
                 return UNITY_SAMPLE_TEX2DARRAY(_BlockTexs, float3(adjusted_tex_uv.x, adjusted_tex_uv.y, texIndex)) * i.color;

             }

            ENDCG
        }
    }
}
