// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

//*********** Strucs ********
struct BlockStateRenderData
{
    int texIndex;
    int animated;
    int numFrames;
    float fps;
    int solid;
    int height;
    int heightTexIndex;
    int heightAnimated;
    int heightExtends;
    
};

struct BlockRenderData
{
    int stateI;
    int rotated;
};

struct Ray
{
    float3 origin;
    float3 dir;
    float3 inv;
};

struct HitInfo
{
    int error;
    int collide;
    float3 coord;
    float3 pos;
    //**********TODO****** add normal
};

float Time;
float3 Sun;

RWTexture2D<float4> Result;
int textureWidth, textureHeight, worldWidth, worldHeight;

StructuredBuffer<BlockRenderData> _BlockDataBuffer;
StructuredBuffer<BlockStateRenderData> _BlockStateDataBuffer;

Texture2DArray<float4> _BlockTexs;
Texture2DArray<float4> _BlockHeightTexs;
SamplerState sampler_BlockTexs;
SamplerState sampler_BlockHeightTexs;

//****** Getting Data ******
int GetIndex(int x, int y, bool ground)
{
    return y * worldWidth + x + (ground ? 0 : worldWidth * worldHeight);
}

int GetIndex(float3 c)
{
    //assumes z is only 1 or 0;
    return c.y * worldWidth + c.x + (c.z == 0 ? 0 : worldWidth * worldHeight);
}

//****** Raytracing ******
//SOURCE: Shadertoy: https://iquilezles.org/articles/intersectors/
HitInfo AABB_Collission(Ray r, float3 boxSize, float3 coord)
{
    HitInfo hit;
    hit.error = 0;
    hit.collide = 0;
    hit.coord = float3(0, 0, 0);
    hit.pos = float3(0, 0, 0);

    const float3 halfExtents = boxSize / 2;
    const float3 centre = coord + halfExtents;
    const float3 ro = r.origin - centre;
    
    const float3 n = r.inv*ro;   // can precompute if traversing a set of aligned boxes
    const float3 k = abs(r.inv)*halfExtents;
    const float3 t1 = -n - k;
    const float3 t2 = -n + k;
    const float tN = max( max( t1.x, t1.y ), t1.z );
    const float tF = min( min( t2.x, t2.y ), t2.z );
    if( tN>tF || tF<0.0) // no intersection
    {
        hit.collide = 0;
        return hit;
    }
    //*******TODO******** Add normal
    // float2 oNormal = (tN>0.0) ? step(float2(tN, tN),t1) : // ro ouside the box
    //                        step(t2,float3(tF, tF, tF));  // ro inside the box
    // oNormal *= -sign(r.dir);

    hit.collide = 1;
    hit.coord = coord;
    hit.pos = r.origin + r.dir * tN;

    return hit;
    // return float2( tN, tF );
}

HitInfo TraverseBlock(Ray r, BlockStateRenderData s, float3 coord)
{
    HitInfo hit;
    hit.error = 0;
    hit.collide = 0;
    hit.coord = coord;
    hit.pos = float3(0, 0, 0);

    float inv8 = 0.125; //1/8

    // height = none so never hits (could technically do with height == 8 but wouldnt have pos so just use aabb
    if (s.height == 0) return hit;

    //simple rectangular collision
    if (s.height != 100) return AABB_Collission(r, float3(1, 1, (float) (s.heightExtends == 0 ? s.height : s.heightExtends) * inv8), s.heightExtends == 0 ? coord : float3(coord.xy, coord.z + (s.height - s.heightExtends) * inv8));

    //Custom height collision STARTS HERE
    
    //Finding height texture index
    const int texIndex = s.heightTexIndex + s.heightAnimated * fmod(floor(Time * s.fps), (float) s.numFrames);
    
    const HitInfo wholeBlockHit = AABB_Collission(r, float3(1, 1, 1), coord);
    if (wholeBlockHit.collide == 0) return wholeBlockHit;
    
    const float3 localPos = clamp(wholeBlockHit.pos - coord, 0.001, 0.999);
    float3 subCoord = floor(localPos * 8);
    
    //Step direction based on sign of ray direction
    const float3 step = sign(r.inv); //use inverse instead of dir bc of floating point
    const float3 delta = abs(r.inv) * inv8;

    //Finding xyz planes to collide with
    //  the origin could currently be anywhere within the voxel
    //  if ray direction is negative the next edge collision will be the same as the current coord
    //  if ray direction is positive it will be one more than the coord
    const float3 select = 0.5 + 0.5 * sign(r.inv); //use inverse instead of dir bc of floating point
    const float3 worldPlanes = coord + (subCoord + select) * inv8;

    //Finding t needed to travel to planes along ray direction
    float3 t = (worldPlanes - r.origin) * r.inv;
    
    //Maximum number of steps before exit
    const int maxTrav = 1000000;
    for(int i = 0; i < maxTrav; i++)
    {
        const float3 uv = subCoord * inv8;

        const float4 texSample = _BlockHeightTexs.SampleLevel(sampler_BlockHeightTexs, float3(uv.xy, texIndex), 0.0);

        const float blockHeight = texSample.r;
        
        //collided with object with height`
        if (uv.z < blockHeight && (s.heightExtends == 0 || uv.z >= blockHeight - s.heightExtends * inv8))
        {
            const float3 cuv = coord + uv;
            HitInfo subCoordHit = AABB_Collission(r, float3(inv8, inv8, s.heightExtends == 0 ? blockHeight : s.heightExtends * inv8), s.heightExtends == 0 ? cuv : float3(cuv.xy, cuv.z + (blockHeight - s.heightExtends) * inv8));
            
            // subCoordHit.collide = 1;
            subCoordHit.error = subCoordHit.collide == 0 ? 1 : 0;
            subCoordHit.coord = coord;
            if (subCoordHit.collide == 1) return subCoordHit;//return if hit inside of block!
        }

        //Go the shortest t
        if (t.x < t.y)
        {
            if (t.x < t.z)
            {
                subCoord.x += step.x;
                t.x += delta.x;
            }else
            {
                subCoord.z += step.z;
                t.z += delta.z;
            }
        }else
        {
            if (t.y < t.z)
            {
                subCoord.y += step.y;
                t.y += delta.y;
            }else
            {
                subCoord.z += step.z;
                t.z += delta.z;
            }
        }

        //exited available area
        if (subCoord.x < 0 || subCoord.x > 8 || subCoord.y < 0 || subCoord.y > 8 || subCoord.z < 0 || subCoord.z > 8)
        {
            hit.collide = 0; //false
            return hit;
        }
    }

    //Did not exit or collide within maxTrav so throw error
    hit.error = 1; //true
    return hit;
    
    
    
    hit.error = 1;
    hit.collide = 1;
    // hit.pos = float3(subCoord) / 8; //looks very cool
    return hit;

}

HitInfo Traverse(Ray r)
{
    HitInfo hit;
    hit.error = 0;
    hit.collide = 0;
    hit.coord = float3(0, 0, 0);
    hit.pos = float3(0, 0, 0);

    const HitInfo outerBoundsHit = AABB_Collission(r, float3(worldWidth, worldHeight, 1), float3(0, 0, 0));
    if (outerBoundsHit.collide == 0) return outerBoundsHit;

    //******TODO******* replace with AABB collision
    float3 coord = floor(r.origin);

    //Step direction based on sign of ray direction
    const float3 step = sign(r.inv); //use inverse instead of dir bc of floating point
    const float3 delta = abs(r.inv);

    //Finding xyz planes to collide with
    //  the origin could currently be anywhere within the voxel
    //  if ray direction is negative the next edge collision will be the same as the current coord
    //  if ray direction is positive it will be one more than the coord
    const float3 select = 0.5 + 0.5 * sign(r.inv); //use inverse instead of dir bc of floating point
    const float3 planes = coord + select;

    //Finding t needed to travel to planes along ray direction
    float3 t = (planes - r.origin) * r.inv;
    
    //Maximum number of steps before exit
    const int maxTrav = 1000000;
    for(int i = 0; i < maxTrav; i++)
    {
        const BlockRenderData block = _BlockDataBuffer[GetIndex(coord)];
        const BlockStateRenderData state = _BlockStateDataBuffer[block.stateI];

        //collided with object with height
        if (state.height != 0)
        {
            HitInfo blockHit = TraverseBlock(r, state, coord);
            
            if (blockHit.collide == 1) return blockHit;//return if hit inside of block!
        }

        //Go the shortest t
        if (t.x < t.y)
        {
            if (t.x < t.z)
            {
                coord.x += step.x;
                t.x += delta.x;
            }else
            {
                coord.z += step.z;
                t.z += delta.z;
            }
        }else
        {
            if (t.y < t.z)
            {
                coord.y += step.y;
                t.y += delta.y;
            }else
            {
                coord.z += step.z;
                t.z += delta.z;
            }
        }

        //exited available area
        if (coord.x < 0 || coord.x > worldWidth || coord.y < 0 || coord.y > worldHeight || coord.z < 0 || coord.z > 1)
        {
            hit.collide = 0; //false
            return hit;
        }
    }

    //Did not exit or collide within maxTrav so throw error
    hit.error = 1; //true
    return hit;
}

//****** Color Manipulation ******

//Written by Claud Sonnet 4.6
float4 AlphaBlend(float4 bottom, float4 top)
{
    float a = top.a + bottom.a * (1.0 - top.a);
    if (a <= 0.0) return float4(0, 0, 0, 0);
    float3 rgb = (top.rgb * top.a + bottom.rgb * bottom.a * (1.0 - top.a)) / a;
    return float4(rgb, a);
}

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    //Calculate UV
    float2 uv = float2((float) id.x / textureWidth, (float) id.y / textureHeight);
    
    // Result[id.xy] = float4(uv.x, uv.y, 0, 1);
    // Result[id.xy] = float4(id.x & id.y, (id.x & 15)/15.0, (id.y & 15)/15.0, 1);

    //Convert to world coord
    const float2 block_uv = float2(uv.x * worldWidth, uv.y * worldHeight);

    //Find spot in texture
    const float2 tex_uv = fmod(block_uv, 1);

    //Get array x and y
    const int2 array_uv = int2((int) block_uv.x, (int) block_uv.y);

    //Getting block array indices
    const int g_block_index = GetIndex(array_uv.x, array_uv.y, true);
    const int ag_block_index = GetIndex(array_uv.x, array_uv.y, false);

    //Getting block information
    const BlockRenderData g_block = _BlockDataBuffer[g_block_index];
    const BlockRenderData ag_block = _BlockDataBuffer[ag_block_index];

    //Getting block state information
    const BlockStateRenderData g_state = _BlockStateDataBuffer[g_block.stateI];
    const BlockStateRenderData ag_state = _BlockStateDataBuffer[ag_block.stateI];
    
    // type.animated is 0 if there is no animation so it will destroy any value generated by the rest of it
    //Getting the index of the texture in _BlockTex
    const float g_texIndex = g_state.texIndex + g_state.animated * fmod(floor(Time * g_state.fps), (float) g_state.numFrames);
    const float ag_texIndex = ag_state.texIndex + ag_state.animated * fmod(floor(Time * ag_state.fps), (float) ag_state.numFrames);

    //Adjusting tex_uv to account for rotation
    const float2 g_adjusted_tex_uv = (g_block.rotated ^ 1) * tex_uv + g_block.rotated * float2(tex_uv.y, tex_uv.x);
    const float2 ag_adjusted_tex_uv = (ag_block.rotated ^ 1) * tex_uv + ag_block.rotated * float2(tex_uv.y, tex_uv.x);

    //Getting color of pixel at the blocks
    const float4 g_col = _BlockTexs.SampleLevel(sampler_BlockTexs, float3(g_adjusted_tex_uv.x, g_adjusted_tex_uv.y, g_texIndex), 0.0);
    const float4 ag_col = _BlockTexs.SampleLevel(sampler_BlockTexs, float3(ag_adjusted_tex_uv.x, ag_adjusted_tex_uv.y, ag_texIndex), 0.0);

    //Combining colors for final color
    const float4 final_col = AlphaBlend(g_col, ag_col);

    float height = 1;

    if (ag_state.height != 0)
    {
        const int ag_height_index = ag_state.heightTexIndex + ag_state.heightAnimated * fmod(floor(Time * ag_state.fps), (float) ag_state.numFrames);
        if (ag_state.height != 100)
        {
            height += ag_state.height * 0.125;
        }else
        {
            const float4 ag_height = _BlockHeightTexs.SampleLevel(sampler_BlockHeightTexs, float3(ag_adjusted_tex_uv.x, ag_adjusted_tex_uv.y, ag_height_index), 0.0);
            height += ag_height.r;
        }
    }

    const float3 origin = float3(block_uv.x, block_uv.y, height); //solid ? 2 : 1
    Ray sunRay;
    sunRay.origin = origin;
    sunRay.dir = Sun;
    sunRay.inv = 1 / sunRay.dir;

    HitInfo hit = Traverse(sunRay);

    const float4 errorColor = float4(1, 0, 1, 1);
    const float4 shadowAdjustedColor = final_col * (1 - 0.5 * hit.collide);
    
    Result[id.xy] = hit.error * errorColor + (1 ^ hit.error) * shadowAdjustedColor;
    // Result[id.xy] = float4(hit.pos, 1);
    // Result[id.xy] = float4(height - 1, 0, 0, 1);
}
